Добавлена версия V1 счетчиков HTTP сервера
happywbfriends/metrics pull request #1
Opened 2023-08-11 13:29 UTC by strannik27

2023-08-11 14:40 UTC, kogleron commented on metrics/http_srv_rq_v1.go
> +type HTTPServerRequestMetricsV1 interface {
Предлагаю делать версии через пакеты, а не имена структур

2023-08-11 14:44 UTC, kogleron commented on metrics/http_srv_rq_v1.go
> +type httpServerRequestMetricsV1 struct {
А current_conns решили не делать?

2023-08-12 08:31 UTC, strannik27 commented on metrics/http_srv_rq_v1.go
> +type HTTPServerRequestMetricsV1 interface {
> Предлагаю делать версии через пакеты, а не имена структур

Я пока сделал в первом приближении

2023-08-12 08:35 UTC, strannik27 commented on metrics/http_srv_rq_v1.go
> +type httpServerRequestMetricsV1 struct {
> current_conns

current_conns есть в httpServerMetrics, но не в httpServerRequestMetrics. Да, в новой версии надо сделать в одном ифейсе.

2023-08-12 08:37 UTC, kogleron commented on metrics/http_srv_rq_v1.go
> +type HTTPServerRequestMetricsV1 interface {
А что это значит относительно моего комментария?
Будет исправлено или нет?

2023-08-14 08:15 UTC, strannik27 commented on metrics/http_srv_rq_v1.go
> +type HTTPServerRequestMetricsV1 interface {
> А что это значит относительно моего комментария? Будет исправлено или нет?

Да, переделаю после дейлика

2023-08-14 11:05 UTC, strannik27 commented on v1_example.go
> +				httpServerMetrics.ObserveOkRequestDuration(method, time.Since(timeBegin))
Уже всплывало в задаче, что этой гистограммой есть смысл мерять только запросы с 200 ответами.
Совершенно логично, но добиться этого можно разными способами. Давайте решим, как именно лучше:
* добавить в гистограмму req_duration_ms лейбл status (сейчас его НЕТ в текущем коде, он остался только в описании в вики), но писать туда только 200-е - в графане при этом можно вывести лейбл статус, четко и ясно увидеть там 200, все вопросы у смотрящего отпадут
* не добавлять статус в гистограмму, ObserveRequestDuration вызывать для всех статусов, но сам ObserveRequestDuration внутри себя будет писать только 200-е, т.е. бизнес-логика падает на плечи пакета
* (как сделано сейчас) не добавлять статус в гистограмму, вызывать ObserveOkRequestDuration, только если статус 200, т.е. переложить логику на клиента, при этом у клиента никогда не возникнет вопросов, что именно он считает

2023-08-14 11:11 UTC, strannik27 commented on v1_example.go
> +				httpServerMetrics.ObserveOkRequestDuration(method, supplierOldId, time.Since(timeBegin))
Уже всплывало в задаче, что этой гистограммой есть смысл мерять только запросы с 200 ответами.
Совершенно логично, но добиться этого можно разными способами. Давайте решим, как именно лучше:
* добавить в гистограмму req_duration_ms лейбл status (сейчас его НЕТ в текущем коде, он остался только в описании в вики), но писать туда только 200-е - в графане при этом можно вывести лейбл статус, четко и ясно увидеть там 200, все вопросы у смотрящего отпадут
* не добавлять статус в гистограмму, ObserveRequestDuration вызывать для всех статусов, но сам ObserveRequestDuration внутри себя будет писать только 200-е, т.е. бизнес-логика падает на плечи пакета
* (как сделано сейчас) не добавлять статус в гистограмму, вызывать ObserveOkRequestDuration, только если статус 200, т.е. переложить логику на клиента, при этом у клиента никогда не возникнет вопросов, что именно он считает

2023-08-14 11:12 UTC, strannik27 commented
Штош, давайте смотреть

2023-08-14 12:15 UTC, kogleron requested changes

2023-08-14 12:15 UTC, kogleron commented on v1/http_srv.go
> +	IncNbConnections()
Почему IncNbRequest в единственном числе, а здесь во множественном?

2023-08-14 12:15 UTC, kogleron commented on v1/http_srv.go
> +	ObserveOkRequestDuration(method string, supplierOldId int, duration time.Duration)
Здесь не хватает статуса, тк 400 и тп быстрые ответы будут размывать RT ответов с реальной работой ручек.

2023-08-14 12:16 UTC, dgrapes approved these changes

2023-08-14 12:20 UTC, merged

2023-08-14 12:24 UTC, dgrapes commented on v1/http_srv.go
> +	IncNbConnections()
правильно везде во множественном

2023-08-14 12:25 UTC, dgrapes commented on v1/http_srv.go
> +	ObserveOkRequestDuration(method string, supplierOldId int, duration time.Duration)
давайте 
1) добавим status в эту ручку
2) переименуем ее (уберем Ok из названия)
3) в ручке будем игнорить не 200

2023-08-14 12:28 UTC, kogleron commented on v1/http_srv.go
> +	ObserveOkRequestDuration(method string, supplierOldId int, duration time.Duration)
Если игнорировать все кроме 200, тогда мы потеряем картину в целом о скорости работы нашего сервиса. 

Например rt 500 ошибок может иметь значение при разборе инцидентов

2023-08-14 12:32 UTC, strannik27 commented on v1/http_srv.go
> +	ObserveOkRequestDuration(method string, supplierOldId int, duration time.Duration)
> Если игнорировать все кроме 200, тогда мы потеряем картину в целом о скорости работы нашего сервиса.
> 
> Например rt 500 ошибок может иметь значение при разборе инцидентов

Это аргумент. Я бы оставил 200 и 500.